import { useEffect,useState } from "react";
import { CommercialAdminCatalog,CommercialProfessional,createCommercialPractice,createCommercialSpecialty,getCommercialAdminCatalog,getConfiguration,listProfessionalLocationAssignments,Location,setProfessionalCommercialProfile,setProfessionalLocations,updateCommercialPractice,updateCommercialSpecialty } from "../../api/supabase";

export function CommercialCatalogManager(){
 const [data,setData]=useState<CommercialAdminCatalog|null>(null);const [specialtyName,setSpecialtyName]=useState("");const [practice,setPractice]=useState({specialty_id:"",name:"",duration_min:15});const [status,setStatus]=useState("");
 const [locations,setLocations]=useState<Location[]>([]);const [links,setLinks]=useState<Array<{professional_id:string;location_id:string}>>([]);
 async function refresh(){const [catalog,config,nextLinks]=await Promise.all([getCommercialAdminCatalog(),getConfiguration(),listProfessionalLocationAssignments()]);setData(catalog);setLocations(config.locations);setLinks(nextLinks);}
 useEffect(()=>{refresh().catch(error=>setStatus(error instanceof Error?error.message:"No se pudo cargar el catalogo."));},[]);
 if(!data)return <section className="panel admin-section wide"><h2>Catalogo publico</h2><p>{status||"Cargando..."}</p></section>;
 return <section className="panel admin-section wide commercial-manager"><div><h2>Catalogo publico</h2><p>Especialidades, practicas, profesionales y lugares publicados.</p></div>
  <div className="commercial-create-grid"><form onSubmit={async e=>{e.preventDefault();if(!specialtyName.trim())return;await createCommercialSpecialty({name:specialtyName});setSpecialtyName("");await refresh();}}><strong>Nueva especialidad</strong><input value={specialtyName} onChange={e=>setSpecialtyName(e.target.value)} placeholder="Ej. Clinica medica"/><button className="primary">Agregar</button></form>
  <form onSubmit={async e=>{e.preventDefault();if(!practice.specialty_id||!practice.name.trim())return;await createCommercialPractice(practice);setPractice({...practice,name:""});await refresh();}}><strong>Nueva practica</strong><select value={practice.specialty_id} onChange={e=>setPractice({...practice,specialty_id:e.target.value})}><option value="">Especialidad</option>{data.specialties.filter(i=>i.active).map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select><input value={practice.name} onChange={e=>setPractice({...practice,name:e.target.value})} placeholder="Nombre"/><select value={practice.duration_min} onChange={e=>setPractice({...practice,duration_min:Number(e.target.value)})}>{Array.from({length:12},(_,i)=>(i+1)*5).map(v=><option key={v} value={v}>{v} min</option>)}</select><button className="primary">Agregar</button></form></div>
  <details open><summary>Especialidades ({data.specialties.length})</summary><div className="commercial-rows">{data.specialties.map(item=><div key={item.id}><strong>{item.name}</strong><label><input type="checkbox" checked={item.published} onChange={async()=>{await updateCommercialSpecialty(item.id,{published:!item.published});await refresh();}}/>Publicada</label><label><input type="checkbox" checked={item.active} onChange={async()=>{await updateCommercialSpecialty(item.id,{active:!item.active});await refresh();}}/>Activa</label></div>)}</div></details>
  <details><summary>Practicas ({data.practices.length})</summary><div className="commercial-rows">{data.practices.map(item=><PracticeRow key={item.id} item={item} specialty={data.specialties.find(s=>s.id===item.specialty_id)?.name||""} onSaved={refresh}/>)}</div></details>
  <details><summary>Profesionales ({data.professionals.length})</summary><div className="commercial-professionals">{data.professionals.map(item=><ProfessionalRow key={item.id} professional={item} data={data} locations={locations} locationIds={links.filter(link=>link.professional_id===item.id).map(link=>link.location_id)} onSaved={refresh}/>)}</div></details>{status&&<p className="notice">{status}</p>}
 </section>;
}

function PracticeRow({item,specialty,onSaved}:{item:CommercialAdminCatalog["practices"][number];specialty:string;onSaved:()=>Promise<void>}){const [form,setForm]=useState(item);return <div className="practice-catalog-row"><strong>{item.name}</strong><span>{specialty} · {item.duration_min} min</span><label><input type="checkbox" checked={form.requires_preparation||false} onChange={e=>setForm({...form,requires_preparation:e.target.checked})}/>Requiere indicaciones</label>{form.requires_preparation&&<input value={form.preparation_instructions||""} onChange={e=>setForm({...form,preparation_instructions:e.target.value})} placeholder="Indicaciones previas"/>}<label><input type="checkbox" checked={form.published} onChange={e=>setForm({...form,published:e.target.checked})}/>Publicada</label><label><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Activa</label><button onClick={async()=>{await updateCommercialPractice(item.id,{published:form.published,active:form.active,requires_preparation:form.requires_preparation,preparation_instructions:form.preparation_instructions});await onSaved();}}>Guardar</button></div>}

function ProfessionalRow({professional,data,locations,locationIds,onSaved}:{professional:CommercialProfessional;data:CommercialAdminCatalog;locations:Location[];locationIds:string[];onSaved:()=>Promise<void>}){const [published,setPublished]=useState(professional.public_booking_enabled);const [specialties,setSpecialties]=useState(professional.specialty_ids);const [practices,setPractices]=useState(professional.practice_ids);const [assigned,setAssigned]=useState(locationIds);const toggle=(list:string[],id:string)=>list.includes(id)?list.filter(v=>v!==id):[...list,id];return <article><div><strong>{professional.full_name}</strong><label><input type="checkbox" checked={published} onChange={e=>setPublished(e.target.checked)}/>Publicado</label></div><fieldset><legend>Especialidades</legend>{data.specialties.filter(i=>i.active).map(i=><label key={i.id}><input type="checkbox" checked={specialties.includes(i.id)} onChange={()=>setSpecialties(toggle(specialties,i.id))}/>{i.name}</label>)}</fieldset><fieldset><legend>Practicas</legend>{data.practices.filter(i=>i.active&&specialties.includes(i.specialty_id)).map(i=><label key={i.id}><input type="checkbox" checked={practices.includes(i.id)} onChange={()=>setPractices(toggle(practices,i.id))}/>{i.name}</label>)}</fieldset><fieldset><legend>Consultorios donde atiende</legend>{locations.filter(i=>i.active).map(i=><label key={i.id}><input type="checkbox" checked={assigned.includes(i.id)} onChange={()=>setAssigned(toggle(assigned,i.id))}/>{i.name}</label>)}</fieldset><button className="primary" onClick={async()=>{await setProfessionalCommercialProfile({professional_id:professional.id,published,specialty_ids:specialties,practice_ids:practices});await setProfessionalLocations(professional.id,assigned);await onSaved();}}>Guardar publicacion</button></article>}
