import { FormEvent, useEffect, useState } from "react";
import { CommercialOrganization, CommercialPlan, createUserWithLogin, getMasterOrganizationCatalog, masterCreateOrganization, masterSaveCommercialPlan, masterUpdateOrganizationCommercial, OrganizationCommercialCatalog } from "../../api/supabase";

const emptyCatalog:OrganizationCommercialCatalog={plans:[],organizations:[]};

export function OrganizationOnboardingManager(){
 const [data,setData]=useState(emptyCatalog);const [status,setStatus]=useState("");const [creating,setCreating]=useState(false);
 const [form,setForm]=useState({commercial_name:"",slug:"",legal_name:"",tax_id:"",email:"",phone:"",responsible_name:"",responsible_email:"",plan_id:""});
 async function refresh(){setData(await getMasterOrganizationCatalog());}
 useEffect(()=>{refresh().catch(e=>setStatus(e instanceof Error?e.message:"No se pudieron cargar los clientes."));},[]);
 async function create(event:FormEvent){event.preventDefault();if(!form.commercial_name.trim()||!form.plan_id)return setStatus("Completa nombre comercial y plan.");setCreating(true);setStatus("");try{await masterCreateOrganization(form);setForm({commercial_name:"",slug:"",legal_name:"",tax_id:"",email:"",phone:"",responsible_name:"",responsible_email:"",plan_id:""});await refresh();setStatus("Organizacion creada en configuracion. Ahora crea su primer Administrador.");}catch(e){setStatus(e instanceof Error?e.message:"No se pudo crear la organizacion.");}finally{setCreating(false);}}
 return <div className="organization-onboarding">
  <section className="panel onboarding-create"><div className="section-title"><div><h2>Nuevo cliente</h2><p>Crea la organizacion sin tocar codigo.</p></div></div><form className="form-grid" onSubmit={create}>
   <label>Nombre comercial<input value={form.commercial_name} onChange={e=>setForm({...form,commercial_name:e.target.value})}/></label>
   <label>Identificador publico<input placeholder="centro-ejemplo" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"-")})}/></label>
   <label>Razon social<input value={form.legal_name} onChange={e=>setForm({...form,legal_name:e.target.value})}/></label><label>CUIT<input value={form.tax_id} onChange={e=>setForm({...form,tax_id:e.target.value})}/></label>
   <label>Email administrativo<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Telefono<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label>
   <label>Responsable<input value={form.responsible_name} onChange={e=>setForm({...form,responsible_name:e.target.value})}/></label><label>Email responsable<input type="email" value={form.responsible_email} onChange={e=>setForm({...form,responsible_email:e.target.value})}/></label>
   <label>Plan<select value={form.plan_id} onChange={e=>setForm({...form,plan_id:e.target.value})}><option value="">Elegir plan</option>{data.plans.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
   <div className="form-actions"><button className="primary" disabled={creating}>{creating?"Creando...":"Crear organizacion"}</button></div>
  </form>{status&&<p className={status.includes("creada")?"notice ok-notice":"error"}>{status}</p>}</section>
  <section className="onboarding-list"><div className="section-title"><div><h2>Organizaciones</h2><p>{data.organizations.length} clientes registrados</p></div></div>{data.organizations.map(org=><OrganizationRow key={org.id} organization={org} plans={data.plans} onSaved={refresh}/>)}</section>
  <PlanManager plans={data.plans} onSaved={refresh}/>
 </div>;
}

function OrganizationRow({organization,plans,onSaved}:{organization:CommercialOrganization;plans:CommercialPlan[];onSaved:()=>Promise<void>}){
 const [form,setForm]=useState({commercial_status:organization.commercial_status,plan_id:organization.plan_id||"",renews_on:organization.renews_on||"",expires_on:organization.expires_on||"",commercial_notes:organization.commercial_notes||"",subscription_status:organization.subscription_status||"ACTIVA"});
 const [message,setMessage]=useState("");const [open,setOpen]=useState(false);
 async function save(){setMessage("");try{await masterUpdateOrganizationCommercial(organization.id,form);await onSaved();setMessage("Cambios guardados.");}catch(e){setMessage(e instanceof Error?e.message:"No se pudo actualizar.");}}
 return <article className={`organization-commercial-card status-${organization.commercial_status.toLowerCase()}`}><button className="organization-card-summary" onClick={()=>setOpen(!open)}><span><strong>{organization.commercial_name}</strong><small>{organization.slug} · {plans.find(p=>p.id===organization.plan_id)?.name||"Sin plan"}</small></span><span><b>{organization.commercial_status}</b><small>{organization.administrators_count} admin · {organization.professionals_count} profesionales · {organization.users_count} usuarios</small></span></button>{open&&<div className="organization-card-body">
  <div className="organization-public-links"><a href={`/?org=${organization.slug}`} target="_blank" rel="noreferrer">Ver home</a><a href={`/turnos?org=${organization.slug}`} target="_blank" rel="noreferrer">Ver turnera</a></div>
  <div className="form-grid"><label>Estado<select value={form.commercial_status} onChange={e=>setForm({...form,commercial_status:e.target.value as CommercialOrganization["commercial_status"]})}><option>CONFIGURACION</option><option>ACTIVA</option><option>SUSPENDIDA</option><option>BAJA</option></select></label><label>Plan<select value={form.plan_id} onChange={e=>setForm({...form,plan_id:e.target.value})}>{plans.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Renovacion<input type="date" value={form.renews_on} onChange={e=>setForm({...form,renews_on:e.target.value})}/></label><label>Vencimiento<input type="date" value={form.expires_on} onChange={e=>setForm({...form,expires_on:e.target.value})}/></label><label className="full-field">Observaciones<textarea value={form.commercial_notes} onChange={e=>setForm({...form,commercial_notes:e.target.value})}/></label></div>
  <div className="plan-usage"><span>Profesionales <b>{organization.professionals_count}</b></span><span>Sedes <b>{organization.centers_count}</b></span><span>Usuarios <b>{organization.users_count}</b></span></div>
  {organization.administrators_count===0&&<FirstAdministrator organizationId={organization.id} onSaved={onSaved}/>}<div className="form-actions"><button className="primary" onClick={()=>void save()}>Guardar estado y plan</button></div>{message&&<p className={message.includes("guardados")?"notice ok-notice":"error"}>{message}</p>}
 </div>}</article>;
}

function FirstAdministrator({organizationId,onSaved}:{organizationId:string;onSaved:()=>Promise<void>}){const [form,setForm]=useState({full_name:"",email:"",document_number:"",password:"",organization_id:organizationId});const [status,setStatus]=useState("");async function submit(e:FormEvent){e.preventDefault();setStatus("");try{const result=await createUserWithLogin({...form,role:"ADMINISTRADOR",location_id:null});setStatus(`${result.profile.full_name} ya puede ingresar.`);await onSaved();}catch(err){setStatus(err instanceof Error?err.message:"No se pudo crear el Administrador.");}}return <form className="first-admin-form" onSubmit={submit}><strong>Primer Administrador</strong><input placeholder="Nombre" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/><input type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder="DNI sin puntos" value={form.document_number} onChange={e=>setForm({...form,document_number:e.target.value.replace(/\D/g,"")})}/><input type="password" placeholder="Clave inicial (8 caracteres)" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button className="primary">Crear Administrador</button>{status&&<small>{status}</small>}</form>}

function PlanManager({plans,onSaved}:{plans:CommercialPlan[];onSaved:()=>Promise<void>}){return <details className="panel plan-manager"><summary>Planes comerciales ({plans.length})</summary><div className="commercial-rows">{plans.map(plan=><PlanRow key={plan.id} plan={plan} onSaved={onSaved}/>)}</div></details>}
function PlanRow({plan,onSaved}:{plan:CommercialPlan;onSaved:()=>Promise<void>}){const [form,setForm]=useState(plan);return <div className="plan-edit-row"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input type="number" title="Profesionales" value={form.max_professionals??""} placeholder="Profesionales" onChange={e=>setForm({...form,max_professionals:e.target.value?Number(e.target.value):null})}/><input type="number" title="Sedes" value={form.max_centers??""} placeholder="Sedes" onChange={e=>setForm({...form,max_centers:e.target.value?Number(e.target.value):null})}/><input type="number" title="Usuarios" value={form.max_internal_users??""} placeholder="Usuarios" onChange={e=>setForm({...form,max_internal_users:e.target.value?Number(e.target.value):null})}/><label><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Activo</label><button onClick={async()=>{await masterSaveCommercialPlan(form);await onSaved();}}>Guardar</button></div>}
