import { FormEvent, useEffect, useMemo, useState } from "react";
import {
  CommercialOrganization, CommercialPlan, createUserWithLogin, getMasterOrganizationCatalog,
  masterCreateOrganization, masterRecordCommercialPayment, masterSaveCommercialPlan,
  masterUpdateOrganizationCommercial, masterVoidCommercialPayment, OrganizationCommercialCatalog,
} from "../../api/supabase";

const emptyCatalog:OrganizationCommercialCatalog={plans:[],organizations:[]};
const money=(amount:number|null|undefined,currency="ARS")=>amount==null?"Sin importe":new Intl.NumberFormat("es-AR",{style:"currency",currency}).format(amount);
const dateLabel=(value:string|null|undefined)=>value?new Intl.DateTimeFormat("es-AR",{timeZone:"America/Argentina/Buenos_Aires"}).format(new Date(`${value}T12:00:00-03:00`)):"Sin fecha";

export function OrganizationOnboardingManager(){
 const [data,setData]=useState(emptyCatalog); const [status,setStatus]=useState(""); const [creating,setCreating]=useState(false);
 const [form,setForm]=useState({commercial_name:"",slug:"",legal_name:"",tax_id:"",email:"",phone:"",responsible_name:"",responsible_email:"",plan_id:""});
 async function refresh(){setData(await getMasterOrganizationCatalog());}
 useEffect(()=>{refresh().catch(e=>setStatus(e instanceof Error?e.message:"No se pudieron cargar los clientes."));},[]);
 const alerts=useMemo(()=>({
   expired:data.organizations.filter(o=>o.subscription_status==="VENCIDA").length,
   due:data.organizations.filter(o=>o.days_remaining!=null&&o.days_remaining>=0&&o.days_remaining<=15).length,
   suspended:data.organizations.filter(o=>o.commercial_status==="SUSPENDIDA"||o.subscription_status==="SUSPENDIDA").length,
 }),[data.organizations]);
 async function create(event:FormEvent){event.preventDefault();if(!form.commercial_name.trim()||!form.plan_id)return setStatus("Completa nombre comercial y plan.");setCreating(true);setStatus("");try{await masterCreateOrganization(form);setForm({commercial_name:"",slug:"",legal_name:"",tax_id:"",email:"",phone:"",responsible_name:"",responsible_email:"",plan_id:""});await refresh();setStatus("Organizacion creada en configuracion. Ahora crea su primer Administrador.");}catch(e){setStatus(e instanceof Error?e.message:"No se pudo crear la organizacion.");}finally{setCreating(false);}}
 return <div className="organization-onboarding">
  <section className="commercial-alert-strip" aria-label="Alertas comerciales"><article><span>Proximas a vencer</span><strong>{alerts.due}</strong></article><article className={alerts.expired?"danger":""}><span>Vencidas</span><strong>{alerts.expired}</strong></article><article className={alerts.suspended?"danger":""}><span>Suspendidas</span><strong>{alerts.suspended}</strong></article></section>
  <details className="panel onboarding-create"><summary>+ Nuevo cliente</summary><form className="form-grid" onSubmit={create}>
   <label>Nombre comercial<input value={form.commercial_name} onChange={e=>setForm({...form,commercial_name:e.target.value})}/></label>
   <label>Identificador publico<input placeholder="centro-ejemplo" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"-")})}/></label>
   <label>Razon social<input value={form.legal_name} onChange={e=>setForm({...form,legal_name:e.target.value})}/></label><label>CUIT<input value={form.tax_id} onChange={e=>setForm({...form,tax_id:e.target.value})}/></label>
   <label>Email administrativo<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Telefono<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label>
   <label>Responsable<input value={form.responsible_name} onChange={e=>setForm({...form,responsible_name:e.target.value})}/></label><label>Email responsable<input type="email" value={form.responsible_email} onChange={e=>setForm({...form,responsible_email:e.target.value})}/></label>
   <label>Plan<select value={form.plan_id} onChange={e=>setForm({...form,plan_id:e.target.value})}><option value="">Elegir plan</option>{data.plans.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
   <div className="form-actions"><button className="primary" disabled={creating}>{creating?"Creando...":"Crear organizacion"}</button></div>
  </form>{status&&<p className={status.includes("creada")?"notice ok-notice":"error"}>{status}</p>}</details>
  <section className="onboarding-list"><div className="section-title"><div><h2>Organizaciones</h2><p>{data.organizations.length} clientes registrados</p></div></div>{data.organizations.map(org=><OrganizationRow key={org.id} organization={org} plans={data.plans} onSaved={refresh}/>)}</section>
  <PlanManager plans={data.plans} onSaved={refresh}/>
 </div>;
}

function OrganizationRow({organization,plans,onSaved}:{organization:CommercialOrganization;plans:CommercialPlan[];onSaved:()=>Promise<void>}){
 const [form,setForm]=useState({commercial_status:organization.commercial_status,plan_id:organization.plan_id||"",starts_on:organization.starts_on||"",renews_on:organization.renews_on||"",expires_on:organization.expires_on||"",agreed_amount:organization.agreed_amount?.toString()||"",currency:organization.currency||"ARS",payment_method:organization.payment_method||"",commercial_manager:organization.commercial_manager||"",billing_day:organization.billing_day?.toString()||"",commercial_notes:organization.commercial_notes||"",subscription_status:organization.subscription_status||"ACTIVA",subscription_notes:organization.subscription_notes||"",change_note:""});
 const [message,setMessage]=useState(""); const [open,setOpen]=useState(false);
 async function save(){setMessage("");try{await masterUpdateOrganizationCommercial(organization.id,form);await onSaved();setMessage("Cambios guardados.");}catch(e){setMessage(e instanceof Error?e.message:"No se pudo actualizar.");}}
 const alert=organization.subscription_status==="VENCIDA"?"Vencida":organization.days_remaining!=null&&organization.days_remaining<=15?`Vence en ${organization.days_remaining} dias`:null;
 return <article className={`organization-commercial-card status-${organization.commercial_status.toLowerCase()}`}>
  <button className="organization-card-summary" onClick={()=>setOpen(!open)}><span><strong>{organization.commercial_name}</strong><small>{organization.slug} · {plans.find(p=>p.id===organization.plan_id)?.name||"Sin plan"}</small></span><span>{alert&&<em className="commercial-warning-badge">{alert}</em>}<b>{organization.commercial_status}</b><small>{organization.administrators_count} admin · {organization.professionals_count} profesionales · {organization.users_count} usuarios</small></span></button>
  {open&&<div className="organization-card-body">
   <div className="organization-public-links"><a href={`/?org=${organization.slug}`} target="_blank" rel="noreferrer">Ver home</a><a href={`/turnos?org=${organization.slug}`} target="_blank" rel="noreferrer">Ver turnera</a></div>
   <div className="commercial-contract-grid">
    <label>Estado de la organizacion<select value={form.commercial_status} onChange={e=>setForm({...form,commercial_status:e.target.value as CommercialOrganization["commercial_status"]})}><option>CONFIGURACION</option><option>ACTIVA</option><option>SUSPENDIDA</option><option>BAJA</option></select></label>
    <label>Estado de cuenta<select value={form.subscription_status} onChange={e=>setForm({...form,subscription_status:e.target.value})}><option>PRUEBA</option><option>ACTIVA</option><option>VENCIDA</option><option>SUSPENDIDA</option><option>CANCELADA</option></select></label>
    <label>Plan<select value={form.plan_id} onChange={e=>setForm({...form,plan_id:e.target.value})}>{plans.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
    <label>Importe acordado<input type="number" min="0" step="0.01" value={form.agreed_amount} onChange={e=>setForm({...form,agreed_amount:e.target.value})}/></label>
    <label>Moneda<select value={form.currency} onChange={e=>setForm({...form,currency:e.target.value as "ARS"|"USD"})}><option>ARS</option><option>USD</option></select></label>
    <label>Medio de pago<input value={form.payment_method} placeholder="Transferencia, efectivo..." onChange={e=>setForm({...form,payment_method:e.target.value})}/></label>
    <label>Inicio<input type="date" value={form.starts_on} onChange={e=>setForm({...form,starts_on:e.target.value})}/></label><label>Proxima renovacion<input type="date" value={form.renews_on} onChange={e=>setForm({...form,renews_on:e.target.value})}/></label><label>Vencimiento<input type="date" value={form.expires_on} onChange={e=>setForm({...form,expires_on:e.target.value})}/></label>
    <label>Dia de cobro<input type="number" min="1" max="28" value={form.billing_day} onChange={e=>setForm({...form,billing_day:e.target.value})}/></label><label>Responsable comercial<input value={form.commercial_manager} onChange={e=>setForm({...form,commercial_manager:e.target.value})}/></label>
    <label className="full-field">Nota del cambio<input value={form.change_note} placeholder="Motivo de renovacion, suspension o cambio de plan" onChange={e=>setForm({...form,change_note:e.target.value})}/></label>
    <label className="full-field">Observaciones comerciales<textarea value={form.commercial_notes} onChange={e=>setForm({...form,commercial_notes:e.target.value})}/></label>
   </div>
   <div className="plan-usage"><span>Profesionales <b>{organization.professionals_count}</b></span><span>Sedes <b>{organization.centers_count}</b></span><span>Usuarios <b>{organization.users_count}</b></span><span>Vencimiento <b>{dateLabel(organization.expires_on)}</b></span></div>
   {organization.administrators_count===0&&<FirstAdministrator organizationId={organization.id} onSaved={onSaved}/>}<div className="form-actions"><button className="primary" onClick={()=>void save()}>Guardar contrato</button></div>{message&&<p className={message.includes("guardados")?"notice ok-notice":"error"}>{message}</p>}
   <PaymentPanel organization={organization} onSaved={onSaved}/><HistoryPanel organization={organization}/>
  </div>}
 </article>;
}

function PaymentPanel({organization,onSaved}:{organization:CommercialOrganization;onSaved:()=>Promise<void>}){
 const [form,setForm]=useState({paid_on:new Date().toISOString().slice(0,10),period_from:"",period_to:"",amount:organization.agreed_amount?.toString()||"",currency:organization.currency||"ARS",payment_method:organization.payment_method||"",reference:"",notes:""}); const [message,setMessage]=useState("");
 async function submit(e:FormEvent){e.preventDefault();setMessage("");try{await masterRecordCommercialPayment(organization.id,form);await onSaved();setForm({...form,reference:"",notes:""});setMessage("Cobro registrado.");}catch(err){setMessage(err instanceof Error?err.message:"No se pudo registrar el cobro.");}}
 return <details className="commercial-subpanel"><summary>Cobros manuales ({organization.payments?.length||0})</summary><form className="payment-form" onSubmit={submit}><label>Fecha<input type="date" value={form.paid_on} onChange={e=>setForm({...form,paid_on:e.target.value})}/></label><label>Importe<input required type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Moneda<select value={form.currency} onChange={e=>setForm({...form,currency:e.target.value as "ARS"|"USD"})}><option>ARS</option><option>USD</option></select></label><label>Medio<input value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value})}/></label><label>Periodo desde<input type="date" value={form.period_from} onChange={e=>setForm({...form,period_from:e.target.value})}/></label><label>Periodo hasta<input type="date" value={form.period_to} onChange={e=>setForm({...form,period_to:e.target.value})}/></label><label>Referencia<input value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></label><button className="primary">Registrar cobro</button></form>{message&&<p className={message.includes("registrado")?"notice ok-notice":"error"}>{message}</p>}<div className="payment-list">{(organization.payments||[]).map(payment=><div key={payment.id} className={payment.status==="ANULADO"?"voided":""}><span><strong>{money(payment.amount,payment.currency)}</strong><small>{dateLabel(payment.paid_on)} · {payment.payment_method||"Sin medio"} {payment.reference&&`· ${payment.reference}`}</small></span><b>{payment.status}</b>{payment.status==="REGISTRADO"&&<button onClick={async()=>{const reason=window.prompt("Motivo de la anulacion");if(reason===null)return;await masterVoidCommercialPayment(payment.id,reason);await onSaved();}}>Anular</button>}</div>)}</div></details>;
}

function HistoryPanel({organization}:{organization:CommercialOrganization}){return <details className="commercial-subpanel"><summary>Historial comercial ({organization.commercial_history?.length||0})</summary><div className="commercial-history">{(organization.commercial_history||[]).map(event=><div key={event.id}><b>{event.event_type.replace(/_/g," ")}</b><span>{new Date(event.created_at).toLocaleString("es-AR",{timeZone:"America/Argentina/Buenos_Aires"})}</span><small>{event.notes||"Sin observacion"}</small></div>)}</div></details>}

function FirstAdministrator({organizationId,onSaved}:{organizationId:string;onSaved:()=>Promise<void>}){const [form,setForm]=useState({full_name:"",email:"",document_number:"",password:"",organization_id:organizationId});const [status,setStatus]=useState("");async function submit(e:FormEvent){e.preventDefault();setStatus("");try{const result=await createUserWithLogin({...form,role:"ADMINISTRADOR",location_id:null});setStatus(`${result.profile.full_name} ya puede ingresar.`);await onSaved();}catch(err){setStatus(err instanceof Error?err.message:"No se pudo crear el Administrador.");}}return <form className="first-admin-form" onSubmit={submit}><strong>Primer Administrador</strong><input placeholder="Nombre" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/><input type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder="DNI sin puntos" value={form.document_number} onChange={e=>setForm({...form,document_number:e.target.value.replace(/\D/g,"")})}/><input type="password" placeholder="Clave inicial (8 caracteres)" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button className="primary">Crear Administrador</button>{status&&<small>{status}</small>}</form>}

const blankPlan:CommercialPlan={id:"",name:"",description:"",monthly_price:null,currency:"ARS",support_description:"",max_professionals:null,max_centers:null,max_internal_users:null,max_monthly_appointments:null,patient_portal_enabled:false,institutional_pdf_enabled:true,communications_enabled:true,advanced_dashboard_enabled:false,active:true};
function PlanManager({plans,onSaved}:{plans:CommercialPlan[];onSaved:()=>Promise<void>}){return <details className="panel plan-manager"><summary>Planes comerciales ({plans.length})</summary><div className="plan-catalog"><PlanRow key="new-plan" plan={blankPlan} onSaved={onSaved} isNew/>{plans.map(plan=><PlanRow key={plan.id} plan={plan} onSaved={onSaved}/>)}</div></details>}
function PlanRow({plan,onSaved,isNew=false}:{plan:CommercialPlan;onSaved:()=>Promise<void>;isNew?:boolean}){const [form,setForm]=useState(plan);return <article className={`plan-edit-card ${isNew?"new-plan":""}`}><div><input placeholder={isNew?"Nombre del nuevo plan":"Nombre"} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Descripcion" value={form.description||""} onChange={e=>setForm({...form,description:e.target.value})}/></div><div><label>Precio mensual<input type="number" min="0" step="0.01" value={form.monthly_price??""} onChange={e=>setForm({...form,monthly_price:e.target.value?Number(e.target.value):null})}/></label><label>Moneda<select value={form.currency} onChange={e=>setForm({...form,currency:e.target.value as "ARS"|"USD"})}><option>ARS</option><option>USD</option></select></label><label>Profesionales<input type="number" value={form.max_professionals??""} onChange={e=>setForm({...form,max_professionals:e.target.value?Number(e.target.value):null})}/></label><label>Sedes<input type="number" value={form.max_centers??""} onChange={e=>setForm({...form,max_centers:e.target.value?Number(e.target.value):null})}/></label><label>Usuarios<input type="number" value={form.max_internal_users??""} onChange={e=>setForm({...form,max_internal_users:e.target.value?Number(e.target.value):null})}/></label><label>Turnos/mes<input type="number" value={form.max_monthly_appointments??""} onChange={e=>setForm({...form,max_monthly_appointments:e.target.value?Number(e.target.value):null})}/></label></div><footer><label><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Activo</label><button disabled={!form.name.trim()} onClick={async()=>{await masterSaveCommercialPlan(form);await onSaved();if(isNew)setForm(blankPlan);}}>{isNew?"Crear plan":"Guardar plan"}</button></footer></article>}
