import { useEffect,useMemo,useState } from "react";
import { Appointment,Communication,CommunicationAlert,CommunicationTemplate,createCommunication,getOrganizationSettings,listCommunicationAlerts,listCommunicationTemplates,OrganizationSettings,Patient,Profile,saveCommunicationTemplate } from "../../api/supabase";

export function CommunicationComposer({patient,appointment,profile,onSaved}:{patient:Patient;appointment?:Appointment|null;profile:Profile;onSaved?:()=>void}) {
 const [templates,setTemplates]=useState<CommunicationTemplate[]>([]); const [templateId,setTemplateId]=useState(""); const [channel,setChannel]=useState<Communication["channel"]>("WHATSAPP");
 const [subject,setSubject]=useState("");const [body,setBody]=useState("");const [status,setStatus]=useState<NonNullable<Communication["status"]>>("ENVIADO_MANUAL");const [observation,setObservation]=useState("");const [notice,setNotice]=useState("");
 const [organization,setOrganization]=useState<OrganizationSettings|null>(null);
 useEffect(()=>{listCommunicationTemplates().then(items=>{setTemplates(items.filter(i=>i.active)); const first=items.find(i=>i.active&&i.channel==="WHATSAPP");if(first)apply(first);}).catch(e=>setNotice(e.message));},[]);
 useEffect(()=>{getOrganizationSettings().then(setOrganization).catch(()=>setOrganization(null));},[]);
 const variables=useMemo(()=>communicationVariables(patient,appointment,profile,organization),[patient,appointment,profile,organization]);
 useEffect(()=>{if(organization&&templateId){const selected=templates.find(item=>item.id===templateId);if(selected)apply(selected);}},[organization]);
 function apply(template:CommunicationTemplate){setTemplateId(template.id);setChannel(template.channel);setSubject(render(template.subject,variables));setBody(render(template.body,variables));setNotice("");}
 function changeChannel(next:Communication["channel"]){setChannel(next);const candidate=templates.find(t=>t.channel===next&&(templates.find(x=>x.id===templateId)?.kind===t.kind))||templates.find(t=>t.channel===next);if(candidate)apply(candidate);}
 async function copy(){await navigator.clipboard.writeText(body);setNotice("Mensaje copiado.");}
 function openWhatsapp(){const phone=(patient.phone||"").replace(/\D/g,"");if(!phone)return setNotice("El paciente no tiene WhatsApp cargado.");window.open(`https://wa.me/${phone}?text=${encodeURIComponent(body)}`,"_blank","noopener,noreferrer");}
 function openEmail(){if(!patient.email)return setNotice("El paciente no tiene email cargado.");window.location.href=`mailto:${encodeURIComponent(patient.email)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;}
 async function register(){try{await createCommunication({patient_id:patient.id,appointment_id:appointment?.id,professional_id:appointment?.doctor_id||profile.id,kind:templates.find(t=>t.id===templateId)?.kind||"OTRO",channel,subject,body,status,observation});setNotice("Contacto registrado en la historia del paciente.");onSaved?.();}catch(e){setNotice(e instanceof Error?e.message:"No se pudo registrar.");}}
 return <section className="communication-composer"><div className="communication-head"><div><h3>Comunicar al paciente</h3><small>Prepará el mensaje y registrá el resultado real.</small></div><div className="channel-switch"><button className={channel==="WHATSAPP"?"active":""} onClick={()=>changeChannel("WHATSAPP")}>WhatsApp</button><button className={channel==="EMAIL"?"active":""} onClick={()=>changeChannel("EMAIL")}>Email</button><button className={channel==="PHONE"?"active":""} onClick={()=>changeChannel("PHONE")}>Telefono</button></div></div>
 <div className="communication-grid"><label>Plantilla<select value={templateId} onChange={e=>{const item=templates.find(t=>t.id===e.target.value);if(item)apply(item);}}><option value="">Mensaje libre</option>{templates.filter(t=>t.channel===channel).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Asunto<input value={subject} onChange={e=>setSubject(e.target.value)}/></label><label className="full-field">Mensaje<textarea value={body} onChange={e=>setBody(e.target.value)}/></label><label>Resultado<select value={status} onChange={e=>setStatus(e.target.value as NonNullable<Communication["status"]>)}><option value="PREPARADO">Preparado</option><option value="ENVIADO_MANUAL">Enviado manualmente</option><option value="CONTACTADO">Contactado</option><option value="SIN_RESPUESTA">Sin respuesta</option><option value="FALLIDO">Fallido</option></select></label><label>Observacion<input value={observation} onChange={e=>setObservation(e.target.value)}/></label></div>
 {notice&&<p className="notice">{notice}</p>}<div className="communication-actions"><button onClick={()=>void copy()}>Copiar mensaje</button>{channel==="WHATSAPP"&&<button onClick={openWhatsapp}>Abrir WhatsApp</button>}{channel==="EMAIL"&&<button onClick={openEmail}>Abrir email</button>}<button className="primary" onClick={()=>void register()}>Registrar contacto</button></div></section>;
}

export function CommunicationTemplateManager(){const [items,setItems]=useState<CommunicationTemplate[]>([]);const [message,setMessage]=useState("");const refresh=()=>listCommunicationTemplates().then(setItems).catch(e=>setMessage(e.message));useEffect(()=>{void refresh();},[]);return <section className="panel template-manager"><h2>Plantillas de comunicacion</h2><p className="notice">Variables: {"{{organizacion_nombre}}, {{organizacion_telefono}}, {{organizacion_email}}, {{organizacion_direccion}}, {{organizacion_whatsapp}}, {{paciente_nombre}}, {{profesional_nombre}}, {{especialidad}}, {{practica}}, {{fecha_turno}}, {{hora_turno}}, {{consultorio}}, {{direccion}}, {{indicaciones}}"}</p>{items.map(item=><TemplateRow key={item.id} item={item} onSaved={refresh}/>)}{message&&<p className="error">{message}</p>}</section>}
function TemplateRow({item,onSaved}:{item:CommunicationTemplate;onSaved:()=>void}){const [form,setForm]=useState(item);const [open,setOpen]=useState(false);const [message,setMessage]=useState("");return <article className="template-row"><button className="template-summary" onClick={()=>setOpen(!open)}><span><strong>{form.name}</strong><small>{form.channel} · {form.kind}</small></span><b>{form.active?"Activa":"Inactiva"}</b></button>{open&&<div className="template-edit"><label>Nombre<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Asunto<input value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/></label><label>Mensaje<textarea value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></label><label><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Activa</label><button className="primary" onClick={async()=>{try{await saveCommunicationTemplate(form);setMessage("Guardada.");onSaved();}catch(e){setMessage(e instanceof Error?e.message:"Error");}}}>Guardar plantilla</button>{message&&<small>{message}</small>}</div>}</article>}

export function CommunicationAlerts({onOpenPatient}:{onOpenPatient:(id:string)=>void}){const [items,setItems]=useState<CommunicationAlert[]>([]);useEffect(()=>{listCommunicationAlerts().then(setItems).catch(()=>setItems([]));},[]);return <section className="panel communication-alerts"><div><h2>Alertas operativas</h2><span>{items.length} pendientes</span></div>{items.slice(0,10).map((item,index)=><button key={`${item.kind}-${item.appointment_id||item.patient_id}-${index}`} onClick={()=>onOpenPatient(item.patient_id)}><span><strong>{alertLabel(item.kind)}</strong>{item.title}</span><small>{item.due_at?new Date(item.due_at).toLocaleString("es-AR",{timeZone:"America/Argentina/Buenos_Aires",day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}):item.detail}</small></button>)}{!items.length&&<p className="empty-day">Sin alertas operativas.</p>}</section>}
function alertLabel(kind:string){return kind==="PENDING_CONFIRMATION"?"Confirmar":kind==="UPCOMING_NO_CONTACT"?"Sin contacto":kind==="WEB_PATIENT_PENDING"?"Validar":kind==="CANCELLED_RECENT"?"Cancelado":kind==="MISSING_DOCUMENTATION"?"Documentacion":kind==="PREPARATION_INSTRUCTIONS"?"Indicaciones":"Aviso";}
function render(text:string,values:Record<string,string>){return text.replace(/\{\{([a-z_]+)\}\}/g,(_,key)=>values[key]||"");}
function communicationVariables(patient:Patient,appointment:Appointment|undefined|null,profile:Profile,organization:OrganizationSettings|null){const starts=appointment?new Date(appointment.starts_at):null;const practices=appointment?.appointment_practices?.map(i=>i.practices?.name).filter(Boolean).join(" + ")||appointment?.type||"Consulta";const instructions=appointment?.appointment_practices?.map(i=>i.practices?.preparation_instructions).filter(Boolean).join(" ")||"Confirmar indicaciones con el consultorio.";return {organizacion_nombre:organization?.commercial_name||"",organizacion_telefono:organization?.phone||"",organizacion_email:organization?.email||"",organizacion_direccion:organization?.main_address||"",organizacion_whatsapp:organization?.whatsapp||"",paciente_nombre:`${patient.first_name} ${patient.last_name}`,profesional_nombre:appointment?.doctor?.full_name||profile.full_name,especialidad:appointment?.doctor?.specialty||profile.specialty||"",practica:practices,fecha_turno:starts?starts.toLocaleDateString("es-AR",{timeZone:"America/Argentina/Buenos_Aires"}):"",hora_turno:starts?starts.toLocaleTimeString("es-AR",{timeZone:"America/Argentina/Buenos_Aires",hour:"2-digit",minute:"2-digit"}):"",consultorio:appointment?.locations?.name||profile.location?.name||"",direccion:appointment?.locations?.address||profile.location?.address||"",indicaciones:instructions};}
